Ariel0508/flavor-trail-react

- src/App.jsx
- src/guideLine.jsx
搬運 pages/GuideLine
1. 
1. 尚未加入 nav & footer
> 搬運 pages/GuideLine

- src/App.jsx
- src/allPost.jsx
搬運 pages/AllPost
1. 
1. 尚未加入 nav & footer
> 搬運 pages/AllPost

- layout/event/EventAbout.jsx
- layout/event/EventAgenda.jsx
- layout/event/EventBanner.jsx
- layout/event/EventBreadcrumb.jsx
- layout/event/EventDeliverMeals.jsx
- layout/event/EventMarquee.jsx
- package-lock.json
- pages/event.html
- src/Event.jsx
搬家(新增)活動頁面
1. 搬家活動頁面 (Event)
* 暫無 nav、footer、CTA …等共用區塊
---
[v] 查看 base branch 是否有正確
[v] 這支 PR 是否有明確的標題、內容描述
> 搬家 event (活動頁面)

- package-lock.json
- src/Routes/index.jsx
- src/layouts/Footer.jsx
1. 加入 footer links
2. 加入 account 相關 routes
3. 「我的帳戶」 ->  「我的帳號」
4.  「我的收藏」 ->  「我的追蹤」 因為沒有收藏惹
1. 
---
> Add account-related routes and update footer links for navigation

- src/pages/AllPosts.jsx
> fix loading

- src/components/account/DeletePostModal.jsx
- src/pages/account/AccountPosts.jsx
目前 shareFoodModal 最新進度
1. 
1. 有些 pickup 部份的資料會錯唷~
---
> 目前 shareFoodModal 最新進度

- assets/scss/components/_allnotifylist.scss
- package-lock.json
- package.json
- src/components/ShareFoodModal.jsx
- src/components/account-notify/ApplyModal.jsx
- src/components/account-notify/ReceiveModal.jsx
- src/components/account/AccountFilterStatus.jsx
- src/components/account/CancelApplyModal.jsx
- src/components/account/DeletePostModal.jsx
- src/pages/account/AccountNotifications.jsx
- src/pages/account/AccountPosts.jsx
- src/pages/section/AccountSettingForm.jsx
- src/pages/section/AccountSettingModalPassword.jsx
1. 全部通知頁更新
1. 申請通知 Modal => 可連回原貼文
2.  領取通知 Modal => 輸入領取碼會跟原貼文的領取碼驗證
* 如果領取成功，按鈕會變已領取，並且不能再領一次
* 如果領取錯誤，會提示領取碼不正確
1. 放棄領取會改變狀態為"已取消"，但我還沒做
2. 申請通知按同意後的 Modal 沒有功能，還沒做
---
> Account 全部通知頁 更新

- src/layouts/Footer.jsx
> fix: update account settings link path in footer

- src/components/account-notify/ReceiveModal.jsx
debug 放棄領取的 popover
1. 
1. 
---
> fix 放棄領取 popover

- src/pages/Post.jsx
1. 調整z-index 修正滑動領取區塊覆蓋Navbar
1. 
---
> post內頁調整 滑動領取區塊覆蓋Navbar

- src/components/ShareFoodEditModal.jsx
> fif img path

- .gitignore
- src/components/CircleCTAButton.jsx
- src/components/FoodApplyModal.jsx
- src/components/ShareFoodEditModal.jsx
- src/components/formElements/CityDistrictSelector.jsx
- src/components/formElements/TimePicker.jsx
- src/pages/AllPosts.jsx
- src/pages/Home.jsx
1. fix TimePicker & DatePicker & CircleCTAButton
1. 
---
> fix TimePicker & DatePicker & CircleCTAButton

- assets/scss/all.scss
- assets/scss/layout/_header.scss
- src/layouts/Header.jsx
1. 刪掉空白 `_navbar.scss`
2. 改 account dropdown active 樣式
3. 改 手機版的 account dropdown links
1. 
---
> fix: update header nav links & fix account dropdown active items styles

- src/layouts/Header.jsx
1. 點擊登出後跳出alert但頁面不會跳轉 > 確認登出後會跳轉回首頁
1. 
---
> fix: 點擊登出的頁面跳轉

- src/components/ShareFoodModal.jsx
> update form size

- src/components/account-notify/ReceiveModal.jsx
- src/components/account/AccountFilter.jsx
- src/components/formElements/InputText.jsx
- src/components/formElements/InputTextGroup.jsx
- src/components/formElements/RadioGroup.jsx
- src/components/formElements/SelectBox.jsx
- src/components/formElements/SelectCity.jsx
- src/components/formElements/TextArea.jsx
- src/pages/account/AccountNotifications.jsx
- src/pages/section/AccountSettingForm.jsx
> fix: eslint problems

- src/components/FullScreenLoading.jsx
- src/components/postPage/OtherPosts.jsx
- src/components/postPage/PostComments.jsx
- src/layouts/Front.jsx
- src/pages/Post.jsx
1.  新增useCallback hook 
2. 調整useEffect 相依參數
3. Front.jsx清除不必要console
4. FullScreenLoading bottom打錯字修正
1. 
---
> post頁面 修正ESLint warning項目

- src/components/ShareFoodEditModal.jsx
- src/components/formElements/CityDistrictSelector.jsx
1. fix esLint AllPost.jsx & CityDistrictSelector.jsx
1. 
---
> fix esLint

- assets/scss/components/_allnotify-filter-status.scss
- src/components/CopyUid.jsx
- src/components/ShareFoodModal.jsx
- src/components/account/AccountFilter.jsx
- src/components/formElements/CityDistrictSelector.jsx
- src/components/formElements/SelectBox.jsx
- src/components/formElements/SelectCity.jsx
- src/layouts/Header.jsx
- src/pages/account/AccountNotifications.jsx
- src/pages/account/AccountPosts.jsx
- src/pages/section/AccountSettingModalPassword.jsx
fix: 修改助教提出程式相關問題點
1. 刪除map 內的 <></>
2. sharefoodmodal 元件缺少 type prop
3. sharefoodmodal rows 型別錯誤修正
4. selectbox/selectcity value 調整
5. 刪除 defaultProps
6. 修改 Header.jsx TwCities 為 twCities
7. 調整我的帳號 > 修改密碼 modal 跑版
8. 全部通知 > 類型 tab 字級太小，背景圈圈變形問題
9. 我的發文 > 卡片未過期標籤與日期在同一行
10. 調整複製領取碼 icon 顏色
1. 應該無
---
> fix: 修改助教提出程式相關問題點

- src/components/account/ChangePhotoModal.jsx
#65 提到個人設定的大頭照壞掉
1. 已調整，並重新上傳新大頭照
1. 無
---
> fix: 修改個人設定大頭照問題

- src/pages/account/AccountPosts.jsx
刪除手機版 district
1. 刪除手機版 district
1. 無
---
> fix:刪除手機版 district

- src/components/account/ChangePhotoModal.jsx
> fix: photoModal

- src/components/CopyUid.jsx
- src/components/account-notify/ApplyModal.jsx
- src/components/account-notify/ApplyReplyModal.jsx
- src/components/account-notify/ReceiveModal.jsx
- src/pages/account/AccountNotifications.jsx
- src/pages/account/AccountPosts.jsx
已將全部通知頁、我的發文頁型別錯誤問題修正
1. 需要點擊兩次才能打開 modal 之問題
2. 點擊 modal 後會跳出型別問題
3. 我的發文頁 typeError 錯誤訊息
1. 已經拉取 mergeDev 但我這邊的『個人設定』還是跳黃黃
---
> 全部通知頁_型別修正

- src/components/ShareFoodModal.jsx
- src/components/account/DeletePostModal.jsx
- src/pages/account/AccountNotifications.jsx
- src/pages/account/AccountPosts.jsx
- src/pages/account/AccountSetting.jsx
debug: 修復刪除貼文功能
1. 其他 modal 已移除 bootstrap 控制 modal 功能，這個忘記了…
2. 第三點樣式問題是因為有寫判斷已讀或未讀 (isRead)
3. ShareFoodModal 裡面日期選擇器已修復
1. 無
---
> fix: 20250416 助教 codereview Account 部份修改
